import { CommentType, TableName } from '../constant';
import { MigrationInterface, QueryRunner } from 'typeorm';
export class Comments1668911845586 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const items = [
      {
        userId: '19020301',
        sourceId: 3,
        type: CommentType.course,
        comment: 'djt me may',
        time: new Date(),
        isBad: 1,
        isBlock: 0,
      },
      {
        userId: '19020301',
        sourceId: 3,
        type: CommentType.course,
        comment: 'profile của giáo viên rất chất lượng',
        time: new Date(),
        isBad: 0,
        isBlock: 0,
      },
      {
        userId: '19020301',
        sourceId: 3,
        type: CommentType.course,
        comment: 'mấy con lợn ngu này',
        time: new Date(),
        isBad: 1,
        isBlock: 0,
      },
      {
        userId: '19020301',
        sourceId: 3,
        type: CommentType.topic,
        comment: 'thầy nói hơi nhỏ',
        time: new Date(),
        isBad: 0,
        isBlock: 0,
      },
      {
        userId: '19020226',
        sourceId: 3,
        type: CommentType.topic,
        comment: 'giáo viên vô trách nhiệm',
        time: new Date(),
        isBad: 1,
        isBlock: 0,
      },
      {
        userId: '19020231',
        sourceId: 3,
        type: CommentType.topic,
        comment: 'kiến thức trong khóa học rất bổ ích',
        time: new Date(),
        isBad: 0,
        isBlock: 0,
      },
      {
        userId: '19020261',
        sourceId: 3,
        type: CommentType.topic,
        comment: 'nội dung chưa chính xác',
        time: new Date(),
        isBad: 1,
        isBlock: 0,
      },
      {
        userId: '19020261',
        sourceId: 1,
        type: CommentType.course,
        comment: 'ăn cứt bố mày đi',
        time: new Date(),
        isBad: 1,
        isBlock: 1,
      },
      {
        userId: '19020153',
        sourceId: 1,
        type: CommentType.course,
        comment: 'thầy giáo giảng bài rất hay',
        time: new Date(),
        isBad: 0,
        isBlock: 0,
      },
      {
        userId: '19020153',
        sourceId: 2,
        type: CommentType.topic,
        comment: 'nội dung rất bổ ích',
        time: new Date(),
        isBad: 0,
        isBlock: 0,
      },
      {
        userId: '19020276',
        sourceId: 2,
        type: CommentType.topic,
        comment: 'nội dung rất tốt',
        time: new Date(),
        isBad: 0,
        isBlock: 0,
      },
      {
        userId: '19020276',
        sourceId: 1,
        type: CommentType.topic,
        comment: 'Cảm ơn Thầy',
        time: new Date(),
        isBad: 0,
        isBlock: 0,
      },
      {
        userId: '19020276',
        sourceId: 1,
        type: CommentType.course,
        comment: 'Cảm ơn bạn',
        time: new Date(),
        isBad: 0,
        isBlock: 0,
      },
      {
        userId: '19020281',
        sourceId: 4,
        type: CommentType.course,
        comment: 'Cảm ơn bạn',
        time: new Date(),
        isBad: 0,
        isBlock: 0,
      },
      {
        userId: '19020281',
        sourceId: 4,
        type: CommentType.topic,
        comment: 'rất hay',
        time: new Date(),
        isBad: 0,
        isBlock: 0,
      },
      {
        userId: '19020221',
        sourceId: 4,
        type: CommentType.topic,
        comment: 'ngu như con chờ hó',
        time: new Date(),
        isBad: 1,
        isBlock: 1,
      },
      {
        userId: '19020221',
        sourceId: 3,
        type: CommentType.topic,
        comment: 'cái loại mày chỉ có ăn đấm',
        time: new Date(),
        isBad: 1,
        isBlock: 1,
      },
      {
        userId: '19020221',
        sourceId: 3,
        type: CommentType.course,
        comment: 'lộ clip em mèo 2006 dáng đẹp show hàng thủ dâm',
        time: new Date(),
        isBad: 1,
        isBlock: 1,
      },
      {
        userId: '19020221',
        sourceId: 3,
        type: CommentType.course,
        comment: 'thầy cô đang địt nhau kìa',
        time: new Date(),
        isBad: 1,
        isBlock: 1,
      },
      {
        userId: '19020206',
        sourceId: 4,
        type: CommentType.topic,
        comment: 'ngu như bò',
        time: new Date(),
        isBad: 1,
        isBlock: 1,
      },
    ];

    await queryRunner.manager.getRepository(TableName.comment).insert(items);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
