services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: ttlab
      MYSQL_DATABASE: elearning2020

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 5000:5000
