services:
  mysql:
    image: mysql:5.7
    container_name: ${DB_HOST}
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - ${APP_PORT}:${APP_PORT}
