enum ConfigKey {
    SORADEMIC_SERVICE_NAME = 'SORADEMIC_SERVICE_NAME',
    PORT = 'PORT',
    VERSION = 'VERSION',
    BASE_PATH = 'BASE_PATH',
    CORS_WHITELIST = 'CORS_WHITELIST',
    LOG_LEVEL = 'LOG_LEVEL',
    LOG_ROOT_FOLDER = 'LOG_ROOT_FOLDER',
    MONGO_DATABSE_CONNECTION_STRING = 'MONGO_DATABSE_CONNECTION_STRING',
    MONGO_DEBUG = 'MONGO_DEBUG',
    JWT_ACCESS_TOKEN_SECRET_KEY = 'JWT_ACCESS_TOKEN_SECRET_KEY',
    JWT_ACCESS_TOKEN_EXPIRED_IN = 'JWT_ACCESS_TOKEN_EXPIRED_IN',
    JWT_REFRESH_TOKEN_SECRET_KEY = 'JWT_REFRESH_TOKEN_SECRET_KEY',
    JWT_REFRESH_TOKEN_EXPIRED_IN = 'JWT_REFRESH_TOKEN_EXPIRED_IN',
}

export default ConfigKey;
